deathmatch jail map
wallstation13/wallstation13 pull request #2
Opened 2024-08-14 12:43 UTC by mc-oofert

## About The Pull Request

![image](https://github.com/user-attachments/assets/733842b4-9af1-437d-9d0b-f988d425ffdc)

cooked

24 players max
2 loadouts:
prisoner - prisoner with shiv
guard - essentially a prisoner with a vest and helmet and a stun baton with no cell

## Why It's Good For The Game

prisoners killing eachother in cafeteria = fun

## Changelog
:cl:
add: deathmatch prison map
/:cl:

2024-08-14 16:47 UTC, Vect0r2 commented
Hello! I would just like to let you know I am looking at this at the moment! We have quite a bit more setup to go though before I will seriously look though this and make sure it's mergable (and hopefully get some better mappers to look over it). But I will let you know when we are ready to start looking though it.

2024-08-15 16:29 UTC, Sadboysuss requested changes
You need to modularize the code changes, if you can't modularize it then place a comment saying that it's a `wallstation edit`

2024-08-15 16:29 UTC, Sadboysuss commented on _maps/deathmatch/perma_jail.dmm
![image](https://github.com/user-attachments/assets/4ba7a730-2a1c-47a9-bb72-a38c36f947ef)
![image](https://github.com/user-attachments/assets/745b91ec-c964-4b5c-b915-51147bba03ea)
This light looks really odd ingame.

2024-08-15 18:14 UTC, mc-oofert commented on _maps/deathmatch/perma_jail.dmm
called an illusion

2024-08-30 00:40 UTC, closed without merging