Creates modularization guide
wallstation13/wallstation13 pull request #85
Opened 2024-08-18 00:27 UTC by Vect0r2

## About The Pull Request
Adds modularization guide. 

## Why It's Good For The Game
guides are good M'kay?

## Changelog

2024-08-18 09:09 UTC, Sadboysuss requested changes

2024-08-18 09:09 UTC, grungussuss commented on wallstation_modules/guidelines.md
> +## How does a conflict happen?
You give an example but don't explain it fully:
`Merge conflicts occur when competing changes are made to the same line of a file, or when one person edits a file and another person deletes the same file. For more information, see "[About merge conflicts](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/about-merge-conflicts)."` (quote from https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line)

2024-08-18 09:09 UTC, grungussuss commented on wallstation_modules/guidelines.md
> +That works well until we the upstream repo decides to change the same variable
```suggestion
This works well until the upstream repository changes the same lines
```

2024-08-18 09:09 UTC, grungussuss commented on wallstation_modules/guidelines.md
> +This is something we do not want to do manually, and something that we do not trust an automated system to do well. But thankfully there is a simple solution, modularization.
```suggestion
This is something we do not want to do manually, and something that we do not trust an automated system to do well. But thankfully, there is a simple solution, modularization.
```

2024-08-18 09:09 UTC, grungussuss commented on wallstation_modules/guidelines.md
> +How does it work? All it means is that the vast majority of our changes are on ``wallstation_modular/`` folder, which /tg/ does not touch, and any changes that cannot be put into that folder are **CL
```suggestion
How does it work? All that means is that the vast majority of our changes are in the ``wallstation_modules`` folder, which is exclusive to our repository and can't conflict with upstream changes as it does not exist upstream. Any changes that cannot be put into this folder must be **CLEARLY LABELED** where they start and where they end.
```

2024-08-18 09:09 UTC, grungussuss commented on wallstation_modules/guidelines.md
> +And then you'll want to establish your core folder that you'll be working out of which is normally your module ID. E.g. `wallstation_modular/modules/disabler_sniper`
```suggestion
Then establish your core folder from where you'll be applying your changes, which is normally your module ID. E.g. `wallstation_modular/modules/disabler_sniper`
```

2024-08-18 09:09 UTC, grungussuss commented on wallstation_modules/guidelines.md
> +Git doesn't handle conflicts of binary files well at all, therefore changes to core binary files are absolutely forbidden, unless you have a really *really* ***really*** good reason to do otherwise.
you have to explain what kind of binary files you're talking about as sound files and many other files are all binary, for example, from a sound PR:
![image](https://github.com/user-attachments/assets/35499df6-601f-49e2-ae42-a166f3066667)
I don't see any reason why we would absolutely forbid this.

2024-08-18 09:09 UTC, grungussuss commented on wallstation_modules/guidelines.md
> +All assets added by us should be placed into the same modular folder as your code. This means everything is kept inside your module folder, sounds, icons and code files.
```suggestion
All assets added by your changes should be placed into the same modular folder as your code. This means everything is kept inside your module folder, sounds, icons and code files.
```

2024-08-18 09:09 UTC, grungussuss commented on wallstation_modules/guidelines.md
> +  First of all you create your modular folder. E.g. `wallstation_modules/modules/lavalandmob`
```suggestion
  First, create your module folder. E.g. `wallstation_modules/modules/lavalandmob`
```

2024-08-18 09:09 UTC, grungussuss commented on wallstation_modules/guidelines.md
> +  And then you'd want to create sub-folders for each component. E.g. `/code` for code and `/sounds` for sound files and `/icons` for any icon files.
```suggestion
Next,  create sub-folders for each component. E.g. `/code` for code,  `/sounds` for sound files and `/icons` for any icon files.
```

2024-08-18 09:09 UTC, grungussuss commented on wallstation_modules/guidelines.md
> +  After doing this, you'll want to set your references within the code.
```suggestion
  After doing this, set your references within the code.
```

2024-08-18 09:09 UTC, grungussuss commented on wallstation_modules/guidelines.md
> +  This ensures your code is fully modular and will make it easier for future edits.
```suggestion
  This ensures your code is fully modular and will make it easier to ammend and review.
```

2024-08-18 09:09 UTC, grungussuss commented on wallstation_modules/guidelines.md
> +You should always put any modular overrides of icons, sound, code, etc. inside this folder, and it **must** follow the core code folder layout.
```suggestion
Always put any modular overrides of icons, sound, code, etc. inside this folder, it **must** follow the core code folder layout.
```
need clarification what the "core code folder layout" is

2024-08-18 09:09 UTC, grungussuss commented on wallstation_modules/guidelines.md
> +This is to make it easier to figure out what changed about a base file without having to search through proc definitions.
```suggestion
This will make it easier to figure out what changed about a base file without having to search through proc definitions.
```

2024-08-18 09:09 UTC, grungussuss commented on wallstation_modules/guidelines.md
> +The most important thing to remember is unless it is absolutely vital **do not touch core codebase files**.
> core codebase files 

Some people may not understand what a core codebase file is

2024-08-18 09:09 UTC, grungussuss commented on wallstation_modules/guidelines.md
> +In short, most of the modular code will be placed in the subfolders of your main module folder **`wallstation_modules/modules/yourmodule/code/`**, with similar rules as with the assets. Do not mirror
```suggestion
In short, all of the modular code should be placed in the subfolders of your main module folder **`wallstation_modules/modules/yourmodule/code/`**, with similar rules as with the assets. Do not mirror core code folder structures inside your modular folder.
```
> most of the modular code 

if it's not in the modular folder then it's not modular

2024-08-18 09:09 UTC, grungussuss commented on wallstation_modules/guidelines.md
> +Such modules **need** to have a `readme.md` in their folder, containing the following:
we're gonna need a proper template you can copy and paste for the `readme.md` file, Nova has one.

2024-08-18 09:09 UTC, grungussuss commented on wallstation_modules/guidelines.md
> +Note, that it is possible to append code in front, or behind a core proc, in a modular fashion, without editing the original proc, through referring the parent proc, using `. = ..()` or `..()`. And l
```suggestion
Note, that it is possible to append code in front, or behind a core proc, in a modular fashion, without editing the original proc, through referring to the parent proc, using `. = ..()` or `..()`. And likewise, it is possible to add a new var to an existing atom, without editing the core files.
```

2024-08-18 09:09 UTC, grungussuss commented on wallstation_modules/guidelines.md
> +For example: please do not copy paste an entire TG proc into a modular override, make one small change, and then bill it as 'fully modular'. These procs are an absolute nightmare to maintain because
```suggestion
For example: do not copy paste an entire TG proc into a modular override, make one small change, and then bill it as 'fully modular'. These procs are an absolute nightmare to maintain because once something changes upstream you have to update the overridden proc.
```

2024-08-18 09:09 UTC, grungussuss commented on wallstation_modules/guidelines.md
> +To keep it simple, let's assume you wanted to make guns spark when shot, for simulating muzzle flash or whatever other reasons, and you want potentially to use it with all kinds of guns.
```suggestion
To keep it simple, let's assume you wanted to make guns spark when shot, for simulating muzzle flash or whatever other reasons, and you potentially want to use it with all kinds of guns.
```

2024-08-18 09:09 UTC, grungussuss commented on wallstation_modules/guidelines.md
> +  //WALLSTATION EDIT ADDITION BEGIN - SHUTTLE_TOGGLE - (Optional Reason/comment)
```suggestion
  //WALLSTATION EDIT BEGIN - SHUTTLE_TOGGLE - (Optional Reason/comment)
```
We will be saying "WALLSTATION EDIT BEGIN" a lot so if we want to clarify when we're removing something or adding - make a comment

2024-08-18 09:09 UTC, grungussuss commented on wallstation_modules/guidelines.md
> +  //WALLSTATION EDIT ADDITION END
previous comment

2024-08-18 09:09 UTC, grungussuss commented on wallstation_modules/guidelines.md
> +  //WALLSTATION EDIT REMOVAL BEGIN - SHUTTLE_TOGGLE - (Optional Reason/comment)
previous comment

2024-08-18 09:09 UTC, grungussuss commented on wallstation_modules/guidelines.md
> +  //WALLSTATION EDIT REMOVAL BEGIN - SHUTTLE_TOGGLE - (Moved to wallstation_modular/shuttle_toggle/randomverbs.dm)
previous comment

2024-08-18 09:09 UTC, grungussuss commented on wallstation_modules/guidelines.md
> +Due to the way byond loads files, it has become necessary to make a different folder for handling our modular defines.
```suggestion
Due to the way byond loads files, it is necessary to make a different folder for handling our modular defines.
```

2024-08-18 09:09 UTC, grungussuss commented on wallstation_modules/guidelines.md
> +To keep form and ensure most modules are easy to navigate and to keep control of the amount of files and folders being made in the repository, you are required to follow this layout.
```suggestion
To keep ensure most modules are easy to navigate and to keep control of the amount of files and folders being made in the repository, you are required to follow this layout.
```

2024-08-18 09:09 UTC, grungussuss commented on wallstation_modules/guidelines.md
> +Thanks to a bit more scrupulous documentation, it will be immediately obvious what changes were done and where and by which features, things will be a lot less ambiguous and messy.
```suggestion
Thanks to a bit more scrupulous documentation, it will be immediately obvious what changes were done, where and by which commit, things will be a lot less ambiguous and messy.
```

2024-08-18 09:15 UTC, Sadboysuss commented
I haven't slept for 22 hours so there will be mistakes, feel free to comment on the review comments if you disagree with them

2024-08-19 08:47 UTC, Vect0r2 commented on wallstation_modules/guidelines.md
> +Git doesn't handle conflicts of binary files well at all, therefore changes to core binary files are absolutely forbidden, unless you have a really *really* ***really*** good reason to do otherwise.
I mean edit any of the files themselves, and having all of our modified binaries in the modular sections makes it easier to look though.

2024-08-19 08:49 UTC, Vect0r2 commented on wallstation_modules/guidelines.md
> +In short, most of the modular code will be placed in the subfolders of your main module folder **`wallstation_modules/modules/yourmodule/code/`**, with similar rules as with the assets. Do not mirror
I mean the code for whatever module you are coding for.

2024-08-19 08:49 UTC, Vect0r2 commented on wallstation_modules/guidelines.md
> +Such modules **need** to have a `readme.md` in their folder, containing the following:
yep that was my plan

2024-08-21 16:30 UTC, merged