DISABLERING: Disabler Rifle + Disabler SMG Undebarrel Launcher
wallstation13/wallstation13 pull request #91
Opened 2024-08-18 12:52 UTC by DrDiasyl

## About The Pull Request

**Disabler Rifle**: Powerful energy weapon firing disabler beams which deals 50 stamina damage and a 1-second knockdown. Has a 2X scope. It takes 3 seconds to recharge between shoots and has 12 shots capacity.
It can be accessed only by printing a gun kit after doing Tier 4 Beam Weapons research, can only be carried on the back, and requires 2 hands to operate.

**Disabler SMG Underbarrel Grenade Launcher:** Disabler SMG starts with an underbarrel grenade launcher that can take in one grenade. Functions like a normal grenade launcher, just put a flashbang or tear gas in and do a Right-Click to fire the grenade.

And for misc:
- Now all Disabler weapons sprites are more contrasty
- Disabler SMGs now can be accessed by doing a Riot Suppression research
<details>

https://github.com/user-attachments/assets/5f988990-c7de-4bcc-8c5b-d366592691db

https://github.com/user-attachments/assets/8db15bbd-20df-4f40-bc32-51b94bfade0f

</details>

## Why It's Good For The Game
Security never had any kind of long-range weapons, and it is interesting to give them something to snipe people with. Security arsenal is really lacking in something interesting, the last fun thing that was added was Disabler SMG.
Also its really funny how half of the Security arsenal is non-lethal weapons.

Disabler SMG was originally made by me and was inspired by the SMG from Half-Life 2, what I missed from it and a suggestion that I heard was to give it an underbarrel grenade launcher and I did. It's a pretty fun addition, it's not really that different from throwing a cooked flashbang but is more convenient.

## Changelog

:cl:
add: Disabler Rifle: A powerful long-range weapon designed for non-lethal takedowns
add: Disabler SMGs now got a underbarrel grenade launcher, not 40mm grenade launchers
/:cl:

2024-08-18 12:54 UTC, mc-oofert commented
powercreep

2024-08-18 13:04 UTC, Sadboysuss requested changes

2024-08-18 13:04 UTC, grungussuss commented on wallstation_modules/disablering/code/projectiles/guns/grenade_launcher.dm
The disabler SMG is already an incredibly powerful weapon and this just makes it the only good option in non-lethal situations as a flashbang + disabler SMG combo will be impossible to counter without having flashbang immunity.
I'm very hesitant on allowing this underbarrel grenade launcher change unless you can provide a good reason as to why the disabler SMG needs a buff.

2024-08-18 13:04 UTC, grungussuss commented on wallstation_modules/disablering/code/research/techweb/security_nodes.dm
> +		"disabler_smg", // ADDED BY WALLSTATION
guns should not be mass printable, it will lead to situations where security becomes non-reliant on cargo for acquiring new weaponry, thus becoming too powerful.

2024-08-18 13:04 UTC, Sadboysuss commented on wallstation_modules/disablering/code/research/techweb/security_nodes.dm
> +		"disabler_rifle", // ADDED BY WALLSTATION
Really liking the disabler rifle

2024-08-18 13:06 UTC, DrDiasyl commented on wallstation_modules/disablering/code/research/techweb/security_nodes.dm
> +		"disabler_smg", // ADDED BY WALLSTATION
Those are gunkits and still require some kind of effort to turn into a real gun.

Disabler SMG cannot be made without a normal Disabler which is finite, and if they will need more - they still have to use cargo to order them. This is not printing guns really.

2024-08-18 13:08 UTC, DrDiasyl commented on wallstation_modules/disablering/code/projectiles/guns/grenade_launcher.dm
The grenade launcher is not any different from just throwing a flashbang, and I don't think we are going to ban flashbangs any soon.
The underbarrel grenade launcher is just a more flavourful and interesting way to deliver grenades.

Anyway Disabler SMG is not that powerful as it deals less damage than a normal Disabler, its only good for people without good aim as such its a skill issue. Its popularity actually dropped, I seen them being massively bought only when they got added, as such this gives them more flavour you know.

2024-08-18 17:02 UTC, JackEnoff commented
I don't think it's a really good idea to let people have grenade launchers (which can use chem grenades (that includes using **explosive** chem grenades)) incorporated to a stun weapon that can be easily made after bothering science long enough.

2024-08-18 18:24 UTC, Chappyfart commented
oh my sweet sec gyatt

2024-08-18 18:47 UTC, Vect0r2 commented
You are failing integration tests because smoothbore disablers don't have sprites.

2024-08-18 21:19 UTC, JupiterJaeden commented
I fucking love this so much, if it really ends up being overtuned we can always nerf it later. But holy shit these are just so flavorful and fucking fun

2024-08-18 21:22 UTC, JupiterJaeden commented on wallstation_modules/disablering/code/projectiles/guns/grenade_launcher.dm
> The disabler SMG is already an incredibly powerful weapon and this just makes it the only good option in non-lethal situations as a flashbang + disabler SMG combo will be impossible to counter without having flashbang immunity. I'm very hesitant on allowing this underbarrel grenade launcher change unless you can provide a good reason as to why the disabler SMG needs a buff.

Disabler SMGs are not that strong. They're really just about on par with a disabler. They were ordered a lot by security when they first came out just because they were a novelty but nowadays they are barely ordered at all. For something that takes a bit more effort to get, the addition of something like an underbarrel launcher is totally fine. And also fucking sick as hell. It can also only hold 1 grenade (which is something I talked to drdiasyl about and made sure of).

2024-08-18 23:19 UTC, Longestarmlonglaw commented
Allow the rifle to be put in suit storage please.

2024-08-19 22:05 UTC, Sadboysuss requested changes
all of my concerns were addressed, fix the spelling errors and I'll merge it

2024-08-19 22:05 UTC, grungussuss commented on wallstation_modules/disablering/code/crafting/guncrafting.dm
> +	desc = "A suitcase containing the necessary gun parts to tranform a normal disabler into a fully automatic disabler SMG."
```suggestion
	desc = "A suitcase containing the necessary gun parts to transform a normal disabler into a fully automatic disabler SMG."
```

2024-08-19 22:05 UTC, grungussuss commented on wallstation_modules/disablering/code/crafting/guncrafting.dm
> +	desc = "A suitcase containing the necessary gun parts to tranform a normal disabler into a high-precision disabler rifle."
```suggestion
	desc = "A suitcase containing the necessary gun parts to transform a normal disabler into a high-precision disabler rifle."
```

2024-08-19 22:05 UTC, Sadboysuss commented on wallstation_modules/disablering/code/projectiles/guns/stun.dm
> +	. += span_notice("Its undebarrel grenade launcher has [underbarrel.grenades.len] / [underbarrel.max_grenades] grenades loaded.")
```suggestion
	. += span_notice("Its underbarrel grenade launcher has [underbarrel.grenades.len] / [underbarrel.max_grenades] grenades loaded.")
```

2024-08-19 22:05 UTC, Sadboysuss commented on wallstation_modules/disablering/code/projectiles/guns/stun.dm
> +	desc = "An bulky disabler rifle designed for long range non-lethal takedowns, packing quite a punch but taking long-time to recharge."
```suggestion
	desc = "A bulky disabler rifle designed for long range non-lethal takedowns, packing quite a punch but taking a long-time to recharge."
```

2024-08-19 22:05 UTC, Sadboysuss commented on wallstation_modules/disablering/code/projectiles/guns/stun.dm
> +	pb_knockback = 1 // It beam is powerful enough to knockdown for a second, so it makes sense to knock you back a tile Point Blank
```suggestion
	pb_knockback = 1 // Its beam is powerful enough to knockdown for a second, so it makes sense to knock you back a tile Point Blank
```

2024-08-19 22:05 UTC, Sadboysuss commented on wallstation_modules/disablering/code/research/designs/weapon_designs.dm
> +	desc = "The kit for an powerful long-ranged disabler rifle."
```suggestion
	desc = "The kit for a powerful long-ranged disabler rifle."
```

2024-08-19 22:05 UTC, Sadboysuss commented on wallstation_modules/disablering/code/research/designs/weapon_designs.dm
> +	desc = "The kit for an fully automatic disabler SMG."
```suggestion
	desc = "The kit for a fully automatic disabler SMG."
```

2024-08-19 22:24 UTC, DrDiasyl commented
Grammar fixed, all checks finished

Yep that's PR time

2024-08-20 00:05 UTC, GPeckman requested changes
Just a few small nitpicks, everything else looks good. Really excited to use the rifle when this is merged.

2024-08-20 00:05 UTC, GPeckman commented on wallstation_modules/disablering/code/projectiles/ammunition/stun.dm
> +// ORIGINAL FILE: code/modules/projectiles/ammunition/stun.dm
```suggestion
// ORIGINAL FILE: code/modules/projectiles/ammunition/energy/stun.dm
```

2024-08-20 00:05 UTC, GPeckman commented on wallstation_modules/disablering/code/projectiles/guns/stun.dm
> +/obj/item/gun/energy/disabler/add_seclight_point()
```suggestion
/obj/item/gun/energy/disabler/smg/add_seclight_point()
```
Without this change it'll stop normal disablers from having seclights attached.

2024-08-20 16:06 UTC, Sadboysuss commented
Fuck it we ball

2024-08-20 16:06 UTC, merged